def payment_domes():
    print("Payment Options".center(50))
    print("\n")
    print("Press 1. for Credit card".center(50))
    print("Press 2. for Debit card".center(50))
    print("Press 3. for Paytm".center(50))
    pa=str(input("Enter the Payment method u want to choose :"))
    if pa=="1":
        print("Enter Your Credit Card Details")
        chd=str(input("Enter  Name on Card :"))
        print("Enter Expiry Date".center(30))
        emd=str(input("Enter Month :".center(30)))
        eyd=str(input("Enter Year :".center(30)))
        cvvd=int(input("Enter CVV No. :".center(30)))
        print("OTP has been sent to your registered mobile no")
        otpd=int(input("Enter the OTP :".center(30)))
        print("Payment Has Been Done for The Amount","₹", psg*amount)
    elif pa=="2":
             print("Enter Your Credit Card Details")
             chd=str(input("Enter  Name on Card"))
             print("Enter Expiry Date".center(30))
             emd=str(input("Enter Month :".center(30)))
             eyd=str(input("Enter Year :".center(30)))
             cvvd=int(input("Enter CVV No. :".center(30)))
             print("OTP has been sent to your registered mobile no")
             otpd=int(input("Enter the OTP :".center(30)))
             print("Payment Has Been Done for The Amount","₹", psg*amount)
    elif pa=="3":
             print("Enter Details For Paytm :")
             phd=int(input("Enter Your Number :"))
             otpd=int(input("Enter the OTP :".center(50)))
             print("Payment Has Been Done for The Amount","₹", psg*amount)
